from flask import Flask, request, jsonify, send_from_directory
from flask_cors import CORS
import random
import os
import time

# Create the Flask application instance.
app = Flask(__name__)
# Enable CORS to allow the HTML file to communicate with this server.
CORS(app)

# This list contains all the jokes the chatbot will tell.
# It will be used to reset the jokes_to_tell list once all jokes have been used.
all_jokes = [
    "Why don't scientists trust atoms? Because they make up everything!",
    "I'm reading a book on anti-gravity. It's impossible to put down!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you call a fish with no eyes? A fsh!",
    "Why don't skeletons fight each other? They don't have the guts!",
    "I told my wife she should embrace her mistakes. She gave me a hug.",
    "Parallel lines have so much in common. It’s a shame they’ll never meet.",
    "What do you call a fake noodle? An impasta.",
    "Why can't a bicycle stand on its own? It's two tired.",
    "What's the difference between a hippo and a zippo? One is really heavy, the other is a little lighter.",
    "I invented a new word! Plagiarism!",
    "Why did the man fall down the well? Because he couldn't see that well.",
    "What do you call a cow with no legs? Ground beef.",
    "Why was the math book sad? Because it had too many problems.",
    "I used to be a baker, but I couldn't make enough dough.",
    "What do you call a boomerang that won't come back? A stick.",
    "What's orange and sounds like a parrot? A carrot.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "What do you call a sleepwalking nun? A roamin' Catholic.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "Why did the coffee file a police report? It got mugged.",
    "I have a fear of speed bumps. But I'm slowly getting over it.",
    "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
    "What did the zero say to the eight? Nice belt!",
    "Why are ghosts so bad at lying? Because you can see right through them.",
    "Did you hear about the fire at the circus? The heat was in tents!",
    "How do you organize a space party? You planet.",
    "What's a pirate's favorite letter? The C.",
    "Why did the picture go to jail? Because it was framed.",
    "I'm on a seafood diet. I see food, and I eat it.",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "Why did the man with one hand cross the road? To get to the second-hand shop.",
    "Why can't you give Elsa a balloon? Because she'll let it go!",
    "What's the best thing about Switzerland? I don't know, but the flag is a big plus.",
    "What do you call a lazy kangaroo? Pouch potato.",
    "I tried to catch some fog, but I mist.",
    "I'm friends with all 25 letters of the alphabet. I just don't know Y.",
    "Why did the football coach go to the bank? To get his quarterback.",
    "What do you call an alligator in a vest? An investigator.",
    "You know what's difference between You and a software engineer ? Both has no Future without Ai.",
    "Why do programmers prefer dark mode? Because light attracts bugs.",
    "Why don't eggs tell jokes? They'd crack each other up.",
    "What do you call a sad strawberry? A blueberry.",
    "What did one hat say to the other? You stay here, I'll go on ahead.",
    "Why was the stadium so cold? Because it was full of fans.",
    "Why did the bicycle fall over? Because it was two-tired.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "What did the grape do when it got stepped on? It let out a little wine.",
    "Why did the golfer wear two pairs of pants? In case he got a hole in one.",
    "I'm so good at sleeping, I can do it with my eyes closed.",
    "What's a vampire's favorite fruit? A neck-tarine.",
    "Why are there no gambling casinos in Africa? Because there are too many cheetahs.",
    "I went to a restaurant on the moon. The food was great, but there was no atmosphere.",
    "How many tickles does it take to make an octopus laugh? Ten tickles.",
    "What do you call a bear with no teeth? A gummy bear.",
    "What's a ghost's favorite dessert? Ice scream.",
    "What do you call a group of crows? A murder.",
    "What did the buffalo say when his son left for college? Bison.",
    "Why did the man put his money in the freezer? He wanted cold hard cash.",
    "What's a snowman's favorite breakfast? Frosted Flakes.",
    "Why did the banana go to the doctor? It wasn't peeling well.",
    "How do you make a tissue dance? You put a little boogie in it.",
    "What do you call a pile of cats? A meowntain.",
    "What do you get if you cross a chicken with a guitar? A hen that strums.",
    "What did the drummer name his twin daughters? Anna 1, Anna 2.",
    "Why did the computer go to the dentist? It had a Bluetooth.",
    "Why can't you hear a pterodactyl go to the bathroom? Because the 'p' is silent.",
    "I don't trust stairs. They're always up to something.",
    "Why did the bicycle fall over? It was two tired.",
    "What do you call a bear with a sore throat? A gummy bear.",
    "What did the left eye say to the right eye? Between you and me, something smells.",
    "Why don't scientists play hide and seek? Because it’s hard to hide when you're made of atoms.",
    "I’m so good at sleeping, I can do it with my eyes closed.",
    "Why did the man get fired from the calendar factory? He took a few days off.",
    "What's the best time to go to the dentist? Tooth-hurty.",
    "What do you call a magician who has lost his magic? A pedestrian.",
    "Did you hear about the restaurant on the moon? Great food, no atmosphere.",
    "What's the difference between a guitar and a fish? You can tuna fish, but you can't fish a tuna.",
    "Why did the melon jump into the lake? It wanted to be a watermelon.",
    "I told a joke about a paper. It was tearable.",
    "What do you call a sleeping bull? A bulldozer.",
    "Why did the cookie go to the hospital? Because it felt crummy.",
    "What do you call a factory that makes good products? A satisfactory.",
    "What do you call a fake noodle? An impasta.",
    "Why did the student eat his homework? Because his teacher said it was a piece of cake.",
    "I'm on a seafood diet. I see food, and I eat it.",
    "Why do bees have sticky hair? Because they use honeycombs.",
    "What do you get when you cross a snowman with a dog? Frostbite.",
    "Did you hear about the kidnapping at the playground? They woke up.",
    "What did one toilet say to the other? You look a bit flushed.",
    "I used to be a baker, but I couldn't make enough dough.",
    "What do you call a cow with no legs? Ground beef.",
    "Why did the scarecrow win an award? He was outstanding in his field.",
    "What do you call a bear with a sore throat? A gummy bear.",
    "I have a fear of speed bumps. But I'm slowly getting over it.",
    "Why are ghosts so bad at lying? Because you can see right through them.",
    "Did you hear about the fire at the circus? It was in tents.",
    "How do you organize a space party? You planet.",
    "What's a pirate's favorite letter? The C.",
    "Why did the picture go to jail? Because it was framed.",
    "What did one wall say to the other wall? I'll meet you at the corner.",
    "Why did the coffee file a police report? It got mugged.",
    "Why was the math book sad? Because it had too many problems.",
    "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
    "What did the zero say to the eight? Nice belt!",
    "What's the difference between a hippo and a zippo? One is really heavy, the other is a little lighter.",
    "I invented a new word! Plagiarism!",
    "Why did the man fall down the well? Because he couldn't see that well.",
    "Why do bicycles fall over? Because they're two tired.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "What do you call a sleepwalking nun? A roamin' Catholic.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "What's orange and sounds like a parrot? A carrot.",
    "What do you call a boomerang that won't come back? A stick.",
    "Why did the football coach go to the bank? To get his quarterback.",
    "What do you call an alligator in a vest? An investigator.",
    "You know what's difference between You and a software engineer ? Both has no Future without Ai.",
    "Why don't eggs tell jokes? They'd crack each other up.",
    "What do you call a sad strawberry? A blueberry.",
    "What did one hat say to the other? You stay here, I'll go on ahead.",
    "Why was the stadium so cold? Because it was full of fans.",
    "Why did the bicycle fall over? Because it was two-tired.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "What did the grape do when it got stepped on? It let out a little wine.",
    "Why did the golfer wear two pairs of pants? In case he got a hole in one.",
    "I'm so good at sleeping, I can do it with my eyes closed.",
    "What's a vampire's favorite fruit? A neck-tarine.",
    "Why are there no gambling casinos in Africa? Because there are too many cheetahs.",
    "I went to a restaurant on the moon. The food was great, but there was no atmosphere.",
    "How many tickles does it take to make an octopus laugh? Ten tickles.",
    "What do you call a bear with no teeth? A gummy bear.",
    "What's a ghost's favorite dessert? Ice scream.",
    "What do you call a group of crows? A murder.",
    "What did the buffalo say when his son left for college? Bison.",
    "Why did the man put his money in the freezer? He wanted cold hard cash.",
    "What's a snowman's favorite breakfast? Frosted Flakes.",
    "Why did the banana go to the doctor? It wasn't peeling well.",
    "How do you make a tissue dance? You put a little boogie in it.",
    "What do you call a pile of cats? A meowntain.",
    "What do you get if you cross a chicken with a guitar? A hen that strums.",
    "What did the drummer name his twin daughters? Anna 1, Anna 2.",
    "Why did the computer go to the dentist? It had a Bluetooth.",
    "Why can't you hear a pterodactyl go to the bathroom? Because the 'p' is silent.",
    "I don't trust stairs. They're always up to something.",
    "Why did the bicycle fall over? It was two tired.",
    "What do you call a bear with a sore throat? A gummy bear.",
    "What did the left eye say to the right eye? Between you and me, something smells.",
    "Why don't scientists play hide and seek? Because it’s hard to hide when you're made of atoms.",
    "I’m so good at sleeping, I can do it with my eyes closed.",
    "Why did the man get fired from the calendar factory? He took a few days off.",
    "What's the best time to go to the dentist? Tooth-hurty.",
    "What do you call a magician who has lost his magic? A pedestrian.",
    "Did you hear about the restaurant on the moon? Great food, no atmosphere.",
    "What's the difference between a guitar and a fish? You can tuna fish, but you can't fish a tuna.",
    "Why did the melon jump into the lake? It wanted to be a watermelon.",
    "I told a joke about a paper. It was tearable.",
    "What do you call a sleeping bull? A bulldozer.",
    "Why did the cookie go to the hospital? Because it felt crummy.",
    "What do you call a factory that makes good products? A satisfactory.",
    "What do you call a fake noodle? An impasta.",
    "Why did the student eat his homework? Because his teacher said it was a piece of cake.",
    "I'm on a seafood diet. I see food, and I eat it.",
    "Why do bees have sticky hair? Because they use honeycombs.",
    "What do you get when you cross a snowman with a dog? Frostbite.",
    "Did you hear about the kidnapping at the playground? They woke up.",
    "What did one toilet say to the other? You look a bit flushed.",
    "I used to be a baker, but I couldn't make enough dough.",
    "What do you call a cow with no legs? Ground beef.",
    "Why did the scarecrow win an award? He was outstanding in his field.",
    "What do you call a bear with a sore throat? A gummy bear.",
    "I have a fear of speed bumps. But I'm slowly getting over it.",
    "Why are ghosts so bad at lying? Because you can see right through them.",
    "Did you hear about the fire at the circus? It was in tents.",
    "How do you organize a space party? You planet.",
    "What's a pirate's favorite letter? The C.",
    "Why did the picture go to jail? Because it was framed.",
    "What did one wall say to the other wall? I'll meet you at the corner.",
    "Why did the coffee file a police report? It got mugged.",
    "Why was the math book sad? Because it had too many problems.",
    "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
    "What did the zero say to the eight? Nice belt!",
    "What's the difference between a hippo and a zippo? One is really heavy, the other is a little lighter.",
    "I invented a new word! Plagiarism!",
    "Why did the man fall down the well? Because he couldn't see that well.",
    "Why do bicycles fall over? Because they're two tired.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "What do you call a sleepwalking nun? A roamin' Catholic.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "What's orange and sounds like a parrot? A carrot.",
    "What do you call a boomerang that won't come back? A stick.",
    "Why did the football coach go to the bank? To get his quarterback.",
    "What do you call an alligator in a vest? An investigator.",
    "You know what's difference between You and a software engineer ? Both has no Future without Ai.",
    "Why don't eggs tell jokes? They'd crack each other up.",
    "What do you call a sad strawberry? A blueberry.",
    "What did one hat say to the other? You stay here, I'll go on ahead.",
    "Why was the stadium so cold? Because it was full of fans.",
    "Why did the bicycle fall over? Because it was two-tired.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "What did the grape do when it got stepped on? It let out a little wine.",
    "Why did the golfer wear two pairs of pants? In case he got a hole in one.",
    "I'm so good at sleeping, I can do it with my eyes closed.",
    "What's a vampire's favorite fruit? A neck-tarine.",
    "Why are there no gambling casinos in Africa? Because there are too many cheetahs.",
    "I went to a restaurant on the moon. The food was great, but there was no atmosphere.",
    "How many tickles does it take to make an octopus laugh? Ten tickles.",
    "What do you call a bear with no teeth? A gummy bear.",
    "What's a ghost's favorite dessert? Ice scream.",
    "What do you call a group of crows? A murder.",
    "What did the buffalo say when his son left for college? Bison.",
    "Why did the man put his money in the freezer? He wanted cold hard cash.",
    "What's a snowman's favorite breakfast? Frosted Flakes.",
    "What do you call a magical dog? A labracadabrador.",
    "I'm not a big fan of elevators. I have a lot of ups and downs.",
    "Why are pirates called pirates? Because they arrr!",
    "What do you call a belt made out of watches? A waist of time.",
    "Why did the invisible man turn down the job offer? He couldn't see himself doing it.",
    "I’m reading a book about black holes. It’s got me really sucked in.",
    "What do you call a boomerang that won't come back? A stick.",
    "What's a pirate's favorite letter? The C, but his true love is the Rrrrrr.",
    "What do you get when you cross a snowman and a shark? Frostbite.",
    "Why did the cookie go to the hospital? Because it felt crummy.",
    "I told a joke about a paper. It was tearable.",
    "Why did the man get fired from the calendar factory? He took a few days off.",
    "What do you call a sleeping bull? A bulldozer.",
    "Why did the scarecrow win an award? He was outstanding in his field.",
    "What did the grape do when it got stepped on? It let out a little wine.",
    "I have a fear of speed bumps. But I'm slowly getting over it.",
    "What do you call a boomerang that won't come back? A stick.",
    "What's the best time to go to the dentist? Tooth-hurty.",
    "What do you call a magician who has lost his magic? A pedestrian.",
    "Why can't you give Elsa a balloon? Because she'll let it go!",
    "What's the best thing about Switzerland? I don't know, but the flag is a big plus.",
    "What do you call a lazy kangaroo? Pouch potato.",
    "I tried to catch some fog, but I mist.",
    "I'm friends with all 25 letters of the alphabet. I just don't know Y.",
    "Why did the football coach go to the bank? To get his quarterback.",
    "What do you call an alligator in a vest? An investigator.",
    "Why don't eggs tell jokes? They'd crack each other up.",
    "What do you call a sad strawberry? A blueberry.",
    "What did one hat say to the other? You stay here, I'll go on ahead.",
    "Why was the stadium so cold? Because it was full of fans.",
    "Why did the bicycle fall over? Because it was two-tired.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "What did the grape do when it got stepped on? It let out a little wine.",
    "Why did the golfer wear two pairs of pants? In case he got a hole in one.",
    "I'm so good at sleeping, I can do it with my eyes closed.",
    "What's a vampire's favorite fruit? A neck-tarine.",
    "Why are there no gambling casinos in Africa? Because there are too many cheetahs.",
    "I went to a restaurant on the moon. The food was great, but there was no atmosphere.",
    "How many tickles does it take to make an octopus laugh? Ten tickles.",
    "What do you call a bear with no teeth? A gummy bear.",
    "What's a ghost's favorite dessert? Ice scream.",
    "What do you call a group of crows? A murder.",
    "What did the buffalo say when his son left for college? Bison.",
    "Why did the man put his money in the freezer? He wanted cold hard cash.",
    "What's a snowman's favorite breakfast? Frosted Flakes.",
    "Why did the banana go to the doctor? It wasn't peeling well.",
    "How do you make a tissue dance? You put a little boogie in it.",
    "What do you call a pile of cats? A meowntain.",
    "What do you get if you cross a chicken with a guitar? A hen that strums.",
    "What did the drummer name his twin daughters? Anna 1, Anna 2.",
    "Why did the computer go to the dentist? It had a Bluetooth.",
    "Why can't you hear a pterodactyl go to the bathroom? Because the 'p' is silent.",
    "I don't trust stairs. They're always up to something.",
    "Why did the bicycle fall over? It was two tired.",
    "What do you call a bear with a sore throat? A gummy bear.",
    "What did the left eye say to the right eye? Between you and me, something smells.",
    "Why don't scientists play hide and seek? Because it’s hard to hide when you're made of atoms.",
    "I’m so good at sleeping, I can do it with my eyes closed.",
    "Why did the man get fired from the calendar factory? He took a few days off.",
    "What's the best time to go to the dentist? Tooth-hurty.",
    "What do you call a magician who has lost his magic? A pedestrian.",
    "Did you hear about the restaurant on the moon? Great food, no atmosphere.",
    "What's the difference between a guitar and a fish? You can tuna fish, but you can't fish a tuna.",
    "Why did the melon jump into the lake? It wanted to be a watermelon.",
    "I told a joke about a paper. It was tearable.",
    "What do you call a sleeping bull? A bulldozer.",
    "Why did the cookie go to the hospital? Because it felt crummy.",
    "What do you call a factory that makes good products? A satisfactory.",
    "What do you call a fake noodle? An impasta.",
    "Why did the student eat his homework? Because his teacher said it was a piece of cake.",
    "I'm on a seafood diet. I see food, and I eat it.",
    "Why do bees have sticky hair? Because they use honeycombs.",
    "What do you get when you cross a snowman with a dog? Frostbite.",
    "Did you hear about the kidnapping at the playground? They woke up.",
    "What did one toilet say to the other? You look a bit flushed.",
    "I used to be a baker, but I couldn't make enough dough.",
    "What do you call a cow with no legs? Ground beef.",
    "Why did the scarecrow win an award? He was outstanding in his field.",
    "What do you call a bear with a sore throat? A gummy bear.",
    "I have a fear of speed bumps. But I'm slowly getting over it.",
    "Why are ghosts so bad at lying? Because you can see right through them.",
    "Did you hear about the fire at the circus? It was in tents.",
    "How do you organize a space party? You planet.",
    "What's a pirate's favorite letter? The C.",
    "Why did the picture go to jail? Because it was framed.",
    "What did one wall say to the other wall? I'll meet you at the corner.",
    "Why did the coffee file a police report? It got mugged.",
    "Why was the math book sad? Because it had too many problems.",
    "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
    "What did the zero say to the eight? Nice belt!",
    "What's the difference between a hippo and a zippo? One is really heavy, the other is a little lighter.",
    "I invented a new word! Plagiarism!",
    "Why did the man fall down the well? Because he couldn't see that well.",
    "Why do bicycles fall over? Because they're two tired.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "What do you call a sleepwalking nun? A roamin' Catholic.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "What's orange and sounds like a parrot? A carrot.",
    "What do you call a boomerang that won't come back? A stick.",
    "Why did the football coach go to the bank? To get his quarterback.",
    "What do you call an alligator in a vest? An investigator.",
    "You know what's difference between You and a software engineer ? Both has no Future without Ai.",
    "Why don't eggs tell jokes? They'd crack each other up.",
    "What do you call a sad strawberry? A blueberry.",
    "What did one hat say to the other? You stay here, I'll go on ahead.",
    "Why was the stadium so cold? Because it was full of fans.",
    "Why did the bicycle fall over? Because it was two-tired.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "What did the grape do when it got stepped on? It let out a little wine.",
    "Why did the golfer wear two pairs of pants? In case he got a hole in one.",
    "I'm so good at sleeping, I can do it with my eyes closed.",
    "What's a vampire's favorite fruit? A neck-tarine.",
    "Why are there no gambling casinos in Africa? Because there are too many cheetahs.",
    "I went to a restaurant on the moon. The food was great, but there was no atmosphere.",
    "How many tickles does it take to make an octopus laugh? Ten tickles.",
    "What do you call a bear with no teeth? A gummy bear.",
    "What's a ghost's favorite dessert? Ice scream.",
    "What do you call a group of crows? A murder.",
    "What did the buffalo say when his son left for college? Bison.",
    "Why did the man put his money in the freezer? He wanted cold hard cash.",
    "What's a snowman's favorite breakfast? Frosted Flakes.",
    "Why was the computer cold? It left its Windows open.",
    "What do you call a fish wearing a bowtie? Sophisticated.",
    "Why did the chicken cross the road? To get to the other side.",
    "How do you get a squirrel to like you? Act like a nut.",
    "What do you call a cow that can't moo? A beef jerky.",
    "Why did the girl put a ladder on the roof? She wanted to climb to the top of her game.",
    "I'm on a diet that consists of nothing but carbs and sugar. It's called 'I don't know what I'm doing with my life'.",
    "What do you call a factory that makes good products? Satisfactory.",
    "Why did the man with one hand cross the road? To get to the second-hand shop.",
    "Why did the bicycle fall over? Because it was two tired.",
    "What do you get when you cross a snowman and a shark? Frostbite.",
    "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
    "Why don't eggs tell jokes? They'd crack each other up.",
    "I'm not a big fan of elevators. I have a lot of ups and downs.",
    "What do you call a belt made out of watches? A waist of time.",
    "Why was the stadium so cold? Because it was full of fans.",
    "Why are ghosts bad at lying? Because you can see right through them.",
    "Did you hear about the fire at the circus? It was in tents.",
    "What do you call a sleeping bull? A bulldozer.",
    "What do you call a pile of cats? A meowntain.",
    "Why did the student eat his homework? Because his teacher said it was a piece of cake.",
    "Why did the man with one hand cross the road? To get to the second-hand shop.",
    "What do you call a sad strawberry? A blueberry.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "What did one wall say to the other wall? I'll meet you at the corner.",
    "What do you call a boomerang that won't come back? A stick.",
    "What's the best time to go to the dentist? Tooth-hurty.",
    "Why did the bicycle fall over? It was two tired.",
    "What's orange and sounds like a parrot? A carrot.",
    "What do you call a boomerang that won't come back? A stick.",
    "Why did the man put his money in the freezer? He wanted cold hard cash.",
    "I'm so good at sleeping, I can do it with my eyes closed.",
    "What's a vampire's favorite fruit? A neck-tarine.",
    "How many tickles does it take to make an octopus laugh? Ten tickles.",
    "Why are there no gambling casinos in Africa? Because there are too many cheetahs.",
    "I went to a restaurant on the moon. The food was great, but there was no atmosphere.",
    "What do you call a bear with no teeth? A gummy bear.",
    "What's a ghost's favorite dessert? Ice scream.",
    "What do you call a group of crows? A murder.",
    "What did the buffalo say when his son left for college? Bison.",
    "What's a snowman's favorite breakfast? Frosted Flakes.",
    "Why did the banana go to the doctor? It wasn't peeling well.",
    "How do you make a tissue dance? You put a little boogie in it.",
    "What do you call a pile of cats? A meowntain.",
    "What do you get if you cross a chicken with a guitar? A hen that strums.",
    "What did the drummer name his twin daughters? Anna 1, Anna 2.",
    "Why did the computer go to the dentist? It had a Bluetooth.",
    "Why can't you hear a pterodactyl go to the bathroom? Because the 'p' is silent.",
    "I don't trust stairs. They're always up to something.",
    "Why did the bicycle fall over? It was two tired.",
    "What do you call a bear with a sore throat? A gummy bear.",
    "What did the left eye say to the right eye? Between you and me, something smells.",
    "Why don't scientists play hide and seek? Because it’s hard to hide when you're made of atoms.",
    "I’m so good at sleeping, I can do it with my eyes closed.",
    "Why did the man get fired from the calendar factory? He took a few days off.",
    "What's the best time to go to the dentist? Tooth-hurty.",
    "What do you call a magician who has lost his magic? A pedestrian.",
    "Did you hear about the restaurant on the moon? Great food, no atmosphere.",
    "What's the difference between a guitar and a fish? You can tuna fish, but you can't fish a tuna.",
    "Why did the melon jump into the lake? It wanted to be a watermelon.",
    "I told a joke about a paper. It was tearable.",
    "What do you call a sleeping bull? A bulldozer.",
    "Why did the cookie go to the hospital? Because it felt crummy.",
    "What do you call a factory that makes good products? A satisfactory.",
    "What do you call a fake noodle? An impasta.",
    "Why did the student eat his homework? Because his teacher said it was a piece of cake.",
    "I'm on a seafood diet. I see food, and I eat it.",
    "Why do bees have sticky hair? Because they use honeycombs.",
    "What do you get when you cross a snowman with a dog? Frostbite.",
    "Did you hear about the kidnapping at the playground? They woke up.",
    "What did one toilet say to the other? You look a bit flushed.",
    "I used to be a baker, but I couldn't make enough dough.",
    "What do you call a cow with no legs? Ground beef.",
    "Why did the scarecrow win an award? He was outstanding in his field.",
    "What do you call a bear with a sore throat? A gummy bear.",
    "I have a fear of speed bumps. But I'm slowly getting over it.",
    "Why are ghosts so bad at lying? Because you can see right through them.",
    "Did you hear about the fire at the circus? It was in tents.",
    "How do you organize a space party? You planet.",
    "What's a pirate's favorite letter? The C.",
    "Why did the picture go to jail? Because it was framed.",
    "What did one wall say to the other wall? I'll meet you at the corner.",
    "Why did the coffee file a police report? It got mugged.",
    "Why was the math book sad? Because it had too many problems.",
    "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
    "What did the zero say to the eight? Nice belt!",
    "What's the difference between a hippo and a zippo? One is really heavy, the other is a little lighter.",
    "I invented a new word! Plagiarism!",
    "Why did the man fall down the well? Because he couldn't see that well.",
    "Why do bicycles fall over? Because they're two tired.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "What do you call a sleepwalking nun? A roamin' Catholic.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "What's orange and sounds like a parrot? A carrot.",
    "What do you call a boomerang that won't come back? A stick.",
    "Why did the football coach go to the bank? To get his quarterback.",
    "What do you call an alligator in a vest? An investigator.",
    "You know what's difference between You and a software engineer ? Both has no Future without Ai.",
    "Why don't eggs tell jokes? They'd crack each other up.",
    "What do you call a sad strawberry? A blueberry.",
    "What did one hat say to the other? You stay here, I'll go on ahead.",
    "Why was the stadium so cold? Because it was full of fans.",
    "Why did the bicycle fall over? Because it was two-tired.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "What did the grape do when it got stepped on? It let out a little wine.",
    "Why did the golfer wear two pairs of pants? In case he got a hole in one.",
    "I'm so good at sleeping, I can do it with my eyes closed.",
    "What's a vampire's favorite fruit? A neck-tarine.",
    "Why are there no gambling casinos in Africa? Because there are too many cheetahs.",
    "I went to a restaurant on the moon. The food was great, but there was no atmosphere.",
    "How many tickles does it take to make an octopus laugh? Ten tickles.",
    "What do you call a bear with no teeth? A gummy bear.",
    "What's a ghost's favorite dessert? Ice scream.",
    "What do you call a group of crows? A murder.",
    "What did the buffalo say when his son left for college? Bison.",
    "Why did the man put his money in the freezer? He wanted cold hard cash.",
    "What's a snowman's favorite breakfast? Frosted Flakes.",
    "Why was the computer cold? It left its Windows open.",
    "What do you call a fish wearing a bowtie? Sophisticated.",
    "Why did the chicken cross the road? To get to the other side.",
    "How do you get a squirrel to like you? Act like a nut.",
    "What do you call a cow that can't moo? A beef jerky.",
    "Why did the girl put a ladder on the roof? She wanted to climb to the top of her game.",
    "I'm on a diet that consists of nothing but carbs and sugar. It's called 'I don't know what I'm doing with my life'.",
    "What do you call a factory that makes good products? Satisfactory.",
    "Why did the man with one hand cross the road? To get to the second-hand shop.",
    "Why did the bicycle fall over? Because it was two tired.",
    "What do you get when you cross a snowman and a shark? Frostbite.",
    "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
    "Why don't eggs tell jokes? They'd crack each other up.",
    "I'm not a big fan of elevators. I have a lot of ups and downs.",
    "What do you call a belt made out of watches? A waist of time.",
    "Why was the stadium so cold? Because it was full of fans.",
    "Why are ghosts bad at lying? Because you can see right through them.",
    "Did you hear about the fire at the circus? It was in tents.",
    "What do you call a sleeping bull? A bulldozer.",
    "What do you call a pile of cats? A meowntain.",
    "Why did the student eat his homework? Because his teacher said it was a piece of cake.",
    "Why did the man with one hand cross the road? To get to the second-hand shop.",
    "What do you call a sad strawberry? A blueberry.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "What did one wall say to the other wall? I'll meet you at the corner.",
    "What do you call a boomerang that won't come back? A stick.",
    "What's the best time to go to the dentist? Tooth-hurty.",
    "Why did the bicycle fall over? It was two tired.",
    "What's orange and sounds like a parrot? A carrot.",
    "What do you call a boomerang that won't come back? A stick.",
    "Why did the man put his money in the freezer? He wanted cold hard cash.",
    "I'm so good at sleeping, I can do it with my eyes closed.",
    "What's a vampire's favorite fruit? A neck-tarine.",
    "How many tickles does it take to make an octopus laugh? Ten tickles.",
    "Why are there no gambling casinos in Africa? Because there are too many cheetahs.",
    "I went to a restaurant on the moon. The food was great, but there was no atmosphere.",
    "What do you call a bear with no teeth? A gummy bear.",
    "What's a ghost's favorite dessert? Ice scream.",
    "What do you call a group of crows? A murder.",
    "What did the buffalo say when his son left for college? Bison.",
    "What's a snowman's favorite breakfast? Frosted Flakes.",
    "Why did the computer cold? It left its Windows open.",
    "What do you call a fish wearing a bowtie? Sophisticated.",
    "Why did the chicken cross the road? To get to the other side.",
    "How do you get a squirrel to like you? Act like a nut.",
    "What do you call a cow that can't moo? A beef jerky.",
    "Why did the girl put a ladder on the roof? She wanted to climb to the top of her game.",
    "I'm on a diet that consists of nothing but carbs and sugar. It's called 'I don't know what I'm doing with my life'.",
    "What do you call a factory that makes good products? Satisfactory.",
    "Why did the man with one hand cross the road? To get to the second-hand shop.",
    "Why did the bicycle fall over? Because it was two tired.",
    "What do you get when you cross a snowman and a shark? Frostbite.",
    "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
    "Why don't eggs tell jokes? They'd crack each other up.",
    "I'm not a big fan of elevators. I have a lot of ups and downs.",
    "What do you call a belt made out of watches? A waist of time.",
    "Why was the stadium so cold? Because it was full of fans.",
    "Why are ghosts bad at lying? Because you can see right through them.",
    "Did you hear about the fire at the circus? It was in tents.",
    "What do you call a sleeping bull? A bulldozer.",
    "What do you call a pile of cats? A meowntain.",
    "Why did the student eat his homework? Because his teacher said it was a piece of cake.",
    "Why did the man with one hand cross the road? To get to the second-hand shop.",
    "What do you call a sad strawberry? A blueberry.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "What did one wall say to the other wall? I'll meet you at the corner.",
    "What do you call a boomerang that won't come back? A stick.",
    "What's the best time to go to the dentist? Tooth-hurty.",
    "Why did the bicycle fall over? It was two tired.",
    "What's orange and sounds like a parrot? A carrot.",
    "What do you call a boomerang that won't come back? A stick.",
    "Why did the man put his money in the freezer? He wanted cold hard cash.",
    "I'm so good at sleeping, I can do it with my eyes closed.",
    "What's a vampire's favorite fruit? A neck-tarine.",
    "How many tickles does it take to make an octopus laugh? Ten tickles.",
    "Why are there no gambling casinos in Africa? Because there are too many cheetahs.",
    "I went to a restaurant on the moon. The food was great, but there was no atmosphere.",
    "What do you call a bear with no teeth? A gummy bear.",
    "What's a ghost's favorite dessert? Ice scream.",
    "What do you call a group of crows? A murder.",
    "What did the buffalo say when his son left for college? Bison.",
    "What's a snowman's favorite breakfast? Frosted Flakes.",
    "Why did the computer cold? It left its Windows open.",
    "What do you call a fish wearing a bowtie? Sophisticated.",
    "Why did the chicken cross the road? To get to the other side.",
    "How do you get a squirrel to like you? Act like a nut.",
    "What do you call a cow that can't moo? A beef jerky.",
    "Why did the girl put a ladder on the roof? She wanted to climb to the top of her game.",
    "I'm on a diet that consists of nothing but carbs and sugar. It's called 'I don't know what I'm doing with my life'.",
    "What do you call a factory that makes good products? Satisfactory.",
    "Why did the man with one hand cross the road? To get to the second-hand shop.",
    "Why did the bicycle fall over? Because it was two tired.",
    "What do you get when you cross a snowman and a shark? Frostbite.",
    "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
    "Why don't eggs tell jokes? They'd crack each other up.",
    "I'm not a big fan of elevators. I have a lot of ups and downs.",
    "What do you call a belt made out of watches? A waist of time.",
    "Why was the stadium so cold? Because it was full of fans.",
    "Why are ghosts bad at lying? Because you can see right through them.",
    "Did you hear about the fire at the circus? It was in tents.",
    "What do you call a sleeping bull? A bulldozer.",
    "What do you call a pile of cats? A meowntain.",
    "Why did the student eat his homework? Because his teacher said it was a piece of cake.",
    "Why did the man with one hand cross the road? To get to the second-hand shop.",
    "What do you call a sad strawberry? A blueberry.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "What did one wall say to the other wall? I'll meet you at the corner.",
    "What do you call a boomerang that won't come back? A stick.",
    "What's the best time to go to the dentist? Tooth-hurty.",
    "Why did the bicycle fall over? It was two tired.",
    "What's orange and sounds like a parrot? A carrot.",
    "What do you call a boomerang that won't come back? A stick.",
    "Why did the man put his money in the freezer? He wanted cold hard cash.",
    "I'm so good at sleeping, I can do it with my eyes closed.",
    "What's a vampire's favorite fruit? A neck-tarine.",
    "How many tickles does it take to make an octopus laugh? Ten tickles.",
    "Why are there no gambling casinos in Africa? Because there are too many cheetahs.",
    "I went to a restaurant on the moon. The food was great, but there was no atmosphere.",
    "What do you call a bear with no teeth? A gummy bear.",
    "What's a ghost's favorite dessert? Ice scream.",
    "What do you call a group of crows? A murder.",
    "What did the buffalo say when his son left for college? Bison.",
    "What's a snowman's favorite breakfast? Frosted Flakes.",
    "Why was the computer cold? It left its Windows open.",
    "What do you call a fish wearing a bowtie? Sophisticated.",
    "Why did the chicken cross the road? To get to the other side.",
    "How do you get a squirrel to like you? Act like a nut.",
    "What do you call a cow that can't moo? A beef jerky.",
    "Why did the girl put a ladder on the roof? She wanted to climb to the top of her game.",
    "I'm on a diet that consists of nothing but carbs and sugar. It's called 'I don't know what I'm doing with my life'.",
    "What do you call a factory that makes good products? Satisfactory.",
    "Why did the man with one hand cross the road? To get to the second-hand shop.",
    "Why did the bicycle fall over? Because it was two tired.",
    "What do you get when you cross a snowman and a shark? Frostbite.",
    "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
    "Why don't eggs tell jokes? They'd crack each other up.",
    "I'm not a big fan of elevators. I have a lot of ups and downs.",
    "What do you call a belt made out of watches? A waist of time.",
    "Why was the stadium so cold? Because it was full of fans.",
    "Why are ghosts bad at lying? Because you can see right through them.",
    "Did you hear about the fire at the circus? It was in tents.",
    "What do you call a sleeping bull? A bulldozer.",
    "What do you call a pile of cats? A meowntain.",
    "Why did the student eat his homework? Because his teacher said it was a piece of cake.",
    "Why did the man with one hand cross the road? To get to the second-hand shop.",
    "What do you call a sad strawberry? A blueberry.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "What did one wall say to the other wall? I'll meet you at the corner.",
    "What do you call a boomerang that won't come back? A stick.",
    "What's the best time to go to the dentist? Tooth-hurty.",
    "Why did the bicycle fall over? It was two tired.",
    "What's orange and sounds like a parrot? A carrot.",
    "What do you call a boomerang that won't come back? A stick.",
    "Why did the man put his money in the freezer? He wanted cold hard cash.",
    "I'm so good at sleeping, I can do it with my eyes closed.",
    "What's a vampire's favorite fruit? A neck-tarine.",
    "How many tickles does it take to make an octopus laugh? Ten tickles.",
    "Why are there no gambling casinos in Africa? Because there are too many cheetahs.",
    "I went to a restaurant on the moon. The food was great, but there was no atmosphere.",
    "What do you call a bear with no teeth? A gummy bear.",
    "What's a ghost's favorite dessert? Ice scream.",
    "What do you call a group of crows? A murder.",
    "What did the buffalo say when his son left for college? Bison.",
    "What's a snowman's favorite breakfast? Frosted Flakes.",
    "Why was the computer cold? It left its Windows open.",
    "What do you call a fish wearing a bowtie? Sophisticated.",
    "Why did the chicken cross the road? To get to the other side.",
    "How do you get a squirrel to like you? Act like a nut.",
    "What do you call a cow that can't moo? A beef jerky.",
    "Why did the girl put a ladder on the roof? She wanted to climb to the top of her game.",
    "I'm on a diet that consists of nothing but carbs and sugar. It's called 'I don't know what I'm doing with my life'.",
    "What do you call a factory that makes good products? Satisfactory.",
    "Why did the man with one hand cross the road? To get to the second-hand shop.",
    "Why did the bicycle fall over? Because it was two tired.",
    "What do you get when you cross a snowman and a shark? Frostbite.",
    "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
    "Why don't eggs tell jokes? They'd crack each other up.",
    "I'm not a big fan of elevators. I have a lot of ups and downs.",
    "What do you call a belt made out of watches? A waist of time.",
    "Why was the stadium so cold? Because it was full of fans.",
    "Why are ghosts bad at lying? Because you can see right through them.",
    "Did you hear about the fire at the circus? It was in tents.",
    "What do you call a sleeping bull? A bulldozer.",
    "What do you call a pile of cats? A meowntain.",
    "Why did the student eat his homework? Because his teacher said it was a piece of cake.",
    "Why did the man with one hand cross the road? To get to the second-hand shop.",
    "What do you call a sad strawberry? A blueberry.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "What did one wall say to the other wall? I'll meet you at the corner.",
    "What do you call a boomerang that won't come back? A stick.",
    "What's the best time to go to the dentist? Tooth-hurty.",
    "Why did the bicycle fall over? It was two tired.",
    "What's orange and sounds like a parrot? A carrot.",
    "What do you call a boomerang that won't come back? A stick.",
    "Why did the man put his money in the freezer? He wanted cold hard cash.",
    "I'm so good at sleeping, I can do it with my eyes closed.",
    "What's a vampire's favorite fruit? A neck-tarine.",
    "How many tickles does it take to make an octopus laugh? Ten tickles.",
    "Why are there no gambling casinos in Africa? Because there are too many cheetahs.",
    "I went to a restaurant on the moon. The food was great, but there was no atmosphere.",
    "What do you call a bear with no teeth? A gummy bear.",
    "What's a ghost's favorite dessert? Ice scream.",
    "What do you call a group of crows? A murder.",
    "What did the buffalo say when his son left for college? Bison.",
    "What's a snowman's favorite breakfast? Frosted Flakes.",
    "Why was the computer cold? It left its Windows open.",
    "What do you call a fish wearing a bowtie? Sophisticated.",
    "Why did the chicken cross the road? To get to the other side.",
    "How do you get a squirrel to like you? Act like a nut.",
    "What do you call a cow that can't moo? A beef jerky.",
    "Why did the girl put a ladder on the roof? She wanted to climb to the top of her game.",
    "I'm on a diet that consists of nothing but carbs and sugar. It's called 'I don't know what I'm doing with my life'.",
    "What do you call a factory that makes good products? Satisfactory.",
    "Why did the man with one hand cross the road? To get to the second-hand shop.",
    "Why did the bicycle fall over? Because it was two tired.",
    "What do you get when you cross a snowman and a shark? Frostbite.",
    "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
    "Why don't eggs tell jokes? They'd crack each other up.",
    "I'm not a big fan of elevators. I have a lot of ups and downs.",
    "What do you call a belt made out of watches? A waist of time.",
    "Why was the stadium so cold? Because it was full of fans.",
    "Why are ghosts bad at lying? Because you can see right through them.",
    "Did you hear about the fire at the circus? It was in tents.",
    "What do you call a sleeping bull? A bulldozer.",
    "What do you call a pile of cats? A meowntain.",
    "Why did the student eat his homework? Because his teacher said it was a piece of cake.",
    "Why did the man with one hand cross the road? To get to the second-hand shop.",
    "What do you call a sad strawberry? A blueberry.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "What did one wall say to the other wall? I'll meet you at the corner.",
    "What do you call a boomerang that won't come back? A stick.",
    "What's the best time to go to the dentist? Tooth-hurty.",
    "Why did the bicycle fall over? It was two tired.",
    "What's orange and sounds like a parrot? A carrot.",
    "What do you call a boomerang that won't come back? A stick.",
    "Why did the man put his money in the freezer? He wanted cold hard cash.",
    "I'm so good at sleeping, I can do it with my eyes closed.",
    "What's a vampire's favorite fruit? A neck-tarine.",
    "How many tickles does it take to make an octopus laugh? Ten tickles.",
    "Why are there no gambling casinos in Africa? Because there are too many cheetahs.",
    "I went to a restaurant on the moon. The food was great, but there was no atmosphere.",
    "What do you call a bear with no teeth? A gummy bear.",
    "What's a ghost's favorite dessert? Ice scream.",
    "What do you call a group of crows? A murder.",
    "What did the buffalo say when his son left for college? Bison.",
    "What's a snowman's favorite breakfast? Frosted Flakes."
]


# This list will be used for telling jokes and will be emptied as jokes are used.
# It's initially a copy of all_jokes.
jokes_to_tell = list(all_jokes)

basic_responses = {
    "hello": "Hello there! I can tell you a joke if you like! 😄",
    "hi": "Hi there! Just ask for a joke, and I'll tell you one! 😊",
    "hey": "Hey! Want to hear a joke? 😉",
    "how are you": "I'm a computer program, so I don't have feelings, but I'm operating perfectly. Thanks for asking! 👍",
    "what is your name": "I am a simple joke-telling chatbot. 🤖",
    "thank you": "You're welcome! Is there anything else I can assist you with? �",
    "thanks": "You're welcome! Is there anything else I can assist you with? 🙏",
    "appreciate it": "My pleasure! Just ask for another joke. 😄",
    "bye": "Goodbye! Have a great day. 👋",
    "quit": "Goodbye! Have a great day. 👋"
}

# This route serves the index.html file when you navigate to the base URL.
@app.route('/')
def serve_index():
    # It assumes the index.html file is in the same directory as app.py
    return send_from_directory('.', 'index.html')

@app.route('/chat', methods=['POST'])
def chat():
    global jokes_to_tell
    data = request.json
    user_input = data.get('message', '').lower()
    
    time.sleep(1)  # Simulate a delay to mimic processing time
    # Check for joke requests
    if "joke" in user_input:
        if not jokes_to_tell:
            jokes_to_tell = list(all_jokes)
        
        joke_index = random.randint(0, len(jokes_to_tell) - 1)
        joke = jokes_to_tell.pop(joke_index)
        return jsonify({"response": joke})
    
    # Check for other basic responses
    for keyword, response in basic_responses.items():
        if keyword in user_input:
            return jsonify({"response": response})
            
    return jsonify({"response": "The server is busy, please try later. 😔"})

if __name__ == '__main__':
    # The server will run on port 5500 to match your HTML file's requests.
    app.run(debug=True, port=5500)